"""initial_sync

Revision ID: 4f8a6d321e88
Revises: 
Create Date: 2025-11-23 20:56:50.139879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f8a6d321e88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_summaries_id', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index('ix_course_sections_id', table_name='course_sections')
    op.drop_table('course_sections')
    op.drop_index('ix_table_cells_id', table_name='table_cells')
    op.drop_table('table_cells')
    op.drop_index('ix_images_id', table_name='images')
    op.drop_table('images')
    op.drop_index('ix_page_insights_id', table_name='page_insights')
    op.drop_table('page_insights')
    op.add_column('blocks', sa.Column('semantic_role', sa.String(), nullable=True))
    op.add_column('blocks', sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    op.add_column('blocks', sa.Column('parent_block_id', sa.Integer(), nullable=True))
    op.add_column('blocks', sa.Column('sequence_order', sa.Integer(), nullable=True))
    op.alter_column('blocks', 'type',
               existing_type=postgresql.ENUM('text', 'table', 'image', 'heading', name='blocktype'),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'blocks', 'blocks', ['parent_block_id'], ['id'])
    op.drop_column('blocks', 'image_format')
    op.drop_column('blocks', 'ocr_confidence')
    op.drop_column('blocks', 'caption')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('caption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('ocr_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('image_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.alter_column('blocks', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('text', 'table', 'image', 'heading', name='blocktype'),
               existing_nullable=True)
    op.drop_column('blocks', 'sequence_order')
    op.drop_column('blocks', 'parent_block_id')
    op.drop_column('blocks', 'hierarchy_level')
    op.drop_column('blocks', 'semantic_role')
    op.create_table('summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], name='summaries_section_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='summaries_pkey')
    )
    op.create_index('ix_summaries_id', 'summaries', ['id'], unique=False)
    op.create_table('page_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('charts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('infographics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('key_insights', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('analysis_error', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name='page_insights_page_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='page_insights_pkey'),
    sa.UniqueConstraint('page_id', name='page_insights_page_id_key')
    )
    op.create_index('ix_page_insights_id', 'page_insights', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bbox', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='images_document_id_fkey'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name='images_page_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    op.create_table('table_cells',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('col', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bbox', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_header', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name='table_cells_block_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='table_cells_pkey')
    )
    op.create_index('ix_table_cells_id', 'table_cells', ['id'], unique=False)
    op.create_table('course_sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='course_sections_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='course_sections_pkey')
    )
    op.create_index('ix_course_sections_id', 'course_sections', ['id'], unique=False)
    # ### end Alembic commands ###
