"""enhance_for_milestone_2_3

Revision ID: d6a64881428a
Revises: 57a17d1cbd19
Create Date: 2025-11-29 18:39:08.285242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a64881428a'
down_revision: Union[str, None] = '57a17d1cbd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subchapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chapter_block_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_block_id', sa.Integer(), nullable=True),
    sa.Column('end_block_id', sa.Integer(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['end_block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['start_block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subchapters_id'), 'subchapters', ['id'], unique=False)
    op.create_table('text_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('position_data', sa.JSON(), nullable=True),
    sa.Column('relationship_to_parent', sa.String(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_components_id'), 'text_components', ['id'], unique=False)
    op.add_column('blocks', sa.Column('text_position', sa.JSON(), nullable=True))
    op.add_column('blocks', sa.Column('is_embedded_in_graphic', sa.Boolean(), nullable=True))
    op.add_column('blocks', sa.Column('is_embedded_in_table', sa.Boolean(), nullable=True))
    op.add_column('blocks', sa.Column('parent_graphic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blocks', 'blocks', ['parent_graphic_id'], ['id'])
    op.add_column('questions', sa.Column('subchapter_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('expected_keywords', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'questions', 'subchapters', ['subchapter_id'], ['id'])
    op.add_column('slides', sa.Column('chapter_title', sa.String(), nullable=True))
    op.add_column('slides', sa.Column('subchapter_title', sa.String(), nullable=True))
    op.add_column('slides', sa.Column('contains_graphics', sa.JSON(), nullable=True))
    op.add_column('slides', sa.Column('contains_tables', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slides', 'contains_tables')
    op.drop_column('slides', 'contains_graphics')
    op.drop_column('slides', 'subchapter_title')
    op.drop_column('slides', 'chapter_title')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'expected_keywords')
    op.drop_column('questions', 'subchapter_id')
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.drop_column('blocks', 'parent_graphic_id')
    op.drop_column('blocks', 'is_embedded_in_table')
    op.drop_column('blocks', 'is_embedded_in_graphic')
    op.drop_column('blocks', 'text_position')
    op.drop_index(op.f('ix_text_components_id'), table_name='text_components')
    op.drop_table('text_components')
    op.drop_index(op.f('ix_subchapters_id'), table_name='subchapters')
    op.drop_table('subchapters')
    # ### end Alembic commands ###
